# Generated by Django 5.0.3 on 2024-04-01 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifestyles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestylepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifestylepost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lifestyles.lifestylecategory'),
        ),
    ]
